# Standard MQTT Protocol
listener 1883
protocol mqtt

# WebSockets Protocol
listener 8083
protocol websockets

# Authentication
allow_anonymous true

# Persistence Configuration
persistence true
persistence_location C:/Program Files/mosquitto/data/

# Logging Configuration
log_dest file C:/Program Files/mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
log_timestamp true

# Connection Settings
max_connections -1